# Generated by Django 4.0.4 on 2022-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='danhmuc',
            field=models.CharField(default='sanpham', max_length=30),
        ),
    ]
