# Generated by Django 4.0.4 on 2022-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sanpham_danhmuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='anhsp',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
