# Generated by Django 4.0.4 on 2022-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_donhang_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='phivanchuyen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donhang',
            name='tienhang',
            field=models.IntegerField(default=0),
        ),
    ]
