# Generated by Django 4.0.4 on 2022-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_donhang_phivanchuyen_donhang_tienhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='motadh',
            field=models.TextField(null=True),
        ),
    ]
