# Generated by Django 4.0.4 on 2022-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('tendn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('sodt', models.CharField(max_length=15)),
                ('matkhau', models.CharField(max_length=20)),
                ('diachi', models.TextField()),
                ('hoten', models.CharField(max_length=30)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
