# Generated by Django 4.0.4 on 2022-05-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='diachi',
            field=models.TextField(max_length=200),
        ),
    ]
